In [ ]:
print("반가워!")

반가워!


In [ ]:
!pip install numpy pandas matplotlib

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pit
print(np.__version__)

2.0.2


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pit
print(np.__version__)
print(pd.__version__)
print(pit.__version__)

2.0.2
2.2.2


AttributeError: module 'matplotlib.pyplot' has no attribute '__version__'

In [ ]:
arr = np.array([1, 2, 3])
print(f"arr의 타입: {type(arr)}")


arr의 타입: <class 'numpy.ndarray'>


In [ ]:
print(f"arr의 축의 개수: {arr.ndim}")
print(f"arr의 크기: {arr.shape}")

arr의 축의 개수: 1
arr의 크기: (3,)


In [ ]:
zero_arr = np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
one_arr = np.ones((2,3))
print(one_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
array_default1=np.arange(3)
array_default1

array([0, 1, 2])

In [ ]:
array_default1=np.arange(start=1, stop=4)
array_default1

array([1, 2, 3])

In [ ]:
array1 = np.array([1,2,3])
array1[2]

np.int64(3)

In [ ]:
print('dimension = ', array1.ndim, ' ', 'shape = ', array1.shape)

dimension =  1   shape =  (3,)


In [ ]:
array2 = np.array([[1,2,3], [4,5,6]])
array2[1,2]

np.int64(6)

In [ ]:
print('dimension = ', array2.ndim, ' ', 'shape = ', array2.shape)

dimension =  2   shape =  (2, 3)


In [ ]:
array3 = np.array([[[1,2,3], [4,5,6]],
                   [[7,8,9], [10,11,12]],
                  [[13,14,15], [16,17,18]]])
array3[1,1,2]

np.int64(12)

In [ ]:
print('dimension = ', array3.ndim, ' ', 'shape = ', array3.shape)

dimension =  3   shape =  (3, 2, 3)


In [ ]:
arr1 = np.array([[5,2,7], [4,3,6]])
arr_sort0 = np.sort(arr1, axis = 0)
arr_sort0


array([[4, 2, 6],
       [5, 3, 7]])

In [ ]:
arr_sort0 = np.sort(arr1, axis = 1)
arr_sort0

array([[2, 5, 7],
       [3, 4, 6]])

In [ ]:
array = np.array([[[16,9,3], [4,5,6]],
                   [[7,8,3], [10,20,12]],
                  [[13,15,14], [22,20,-2]]])
np.sort(array, axis = 0)

array([[[ 7,  8,  3],
        [ 4,  5, -2]],

       [[13,  9,  3],
        [10, 20,  6]],

       [[16, 15, 14],
        [22, 20, 12]]])

In [ ]:
arr1 = np.array([[5,2,7], [4,3,6]])
arr1

array([[5, 2, 7],
       [4, 3, 6]])

In [ ]:
arr2 = np.array([[1,2,3], [4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.add(arr1, arr2)

array([[ 6,  4, 10],
       [ 8,  8, 12]])

In [ ]:
arr1 + arr2

array([[ 6,  4, 10],
       [ 8,  8, 12]])

In [ ]:
np.subtract(arr1, arr2)

array([[ 4,  0,  4],
       [ 0, -2,  0]])

In [ ]:
arr1 - arr2

array([[ 4,  0,  4],
       [ 0, -2,  0]])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.dot(a,b))

32


In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6], [7,8]])

print(np.dot(A,B))

[[19 22]
 [43 50]]


In [ ]:
array_default1 = np.arange(6)
array_default1


array([0, 1, 2, 3, 4, 5])

In [ ]:
array_default1.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
array1 = np.zeros((3,2), dtype = 'int32')
array2 = array1.reshape(2,3)
array1

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [ ]:
array2

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [ ]:
array3 = array1.reshape(-1, 3)
array3

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [ ]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9, 10, 11, 12]])
print("전체 평균: ", np.mean(arr))
print("행 기준 평균(axis = 1): ", np.mean(arr, axis=1))
print("열 기준 평균(axis = 0): ", np.mean(arr, axis=0))

전체 평균:  6.5
행 기준 평균(axis = 1):  [ 2.5  6.5 10.5]
열 기준 평균(axis = 0):  [5. 6. 7. 8.]


In [ ]:
arr = np.array([[5,2,7], [4,3,6]])
arr

array([[5, 2, 7],
       [4, 3, 6]])

In [ ]:
arr.sum(axis=0)

array([ 9,  5, 13])

In [ ]:
arr.sum(axis=1)

array([14, 13])

In [ ]:
array4 = np.array([[11,10,3,4],
                  [7,1,2,9],
                  [6,8,5,12]])

In [ ]:
array4.sum(axis=1)

array([28, 19, 31])

In [ ]:
array4.mean(axis=0)

array([8.        , 6.33333333, 3.33333333, 8.33333333])

In [84]:
result = np.sort(array4.reshape(-1)).reshape(3,4)
result

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])